[config.wallpaper]
command = "swww"
#arguments = ["img", "--transition-type", "random", "--transition-step", "255", "--transition-fps", "60", "--transition-duration", "2"]
set = false

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-dark; sleep 1'

[templates.swayosd]
input_path = './templates/colors.css'
output_path = '~/.config/swayosd/colors.css'
post_hook = 'pkill swayosd-server; swayosd-server & disown'

[templates.swaync]
input_path = './templates/colors.css'
output_path = '~/.config/swaync/colors.css'
post_hook = 'pkill swaync; swaync & disown'

[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill waybar; waybar & disown'

[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.rofi]
input_path = './templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.alacritty]
input_path = './templates/alacritty.toml'
output_path = '~/.config/alacritty/colors.toml'

[templates.pywalfox]
input_path = './templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.cava]
input_path = './templates/cava-colors.ini'
output_path = '~/.config/cava/themes/matugen'
post_hook = "pkill -USR1 cava"

[templates.btop]
input_path = './templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill xdg-desktop-por; /usr/lib/xdg-desktop-portal-hyprland & disown'
